class String

  def toANSI()
    x = self.gsub('Á','A')
    x = x.gsub('Č','C')
    x = x.gsub('Ď','D')
    x = x.gsub('Ě','E')
    x = x.gsub('É','E')
    x = x.gsub('Í','I')
    x = x.gsub('Ň','N')
    x = x.gsub('Ó','O')
    x = x.gsub('Ř','R')
    x = x.gsub('Š','S')
    x = x.gsub('Ť','T')
    x = x.gsub('Ú','U')
    x = x.gsub('Ů','U')
    x = x.gsub('Ý','Y')
    x = x.gsub('Ž','Z')
    x = x.gsub('á','a')
    x = x.gsub('č','c')
    x = x.gsub('ď','d')
    x = x.gsub('ě','e')
    x = x.gsub('é','e')
    x = x.gsub('í','i')
    x = x.gsub('ň','n')
    x = x.gsub('ñ','n')
    x = x.gsub('ó','o')
    x = x.gsub('ř','r')
    x = x.gsub('š','s')
    x = x.gsub('ť','t')
    x = x.gsub('ú','u')
    x = x.gsub('ů','u')
    x = x.gsub('ý','y')
    x = x.gsub('ž','z')
    x = x.gsub('ü','u')
  end

end
